version: '3.8'

services:
  translator-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transneft_news_translator
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs
      - ./models:/app/models
    restart: unless-stopped
